---
title: "TheCakeReport"
author: "Sucre roux and Coco l'asticot"
date: "24 mars 2016"
output: 
  pdf_document: 
    toc: yes
---

```{r, fig.width=10}
library(lattice)
setwd("/Users/Ofix/Desktop/tcr/")
grades <- read.csv("grades.csv")

boxplotByCake <- function (cakeName, initData){
  data <- initData[which (initData$cake==cakeName),]
  priceByCookie<-round(data$price[1]/data$nb.of.cookies[1],2)
  par(mar=c(4,4,4,4))
  boxplot(data$aspect, data$taste, data$texture, data$packaging, data$qualityByPrice, 
          ylim=c(0,4), names=names(data[5:9]),
          cex = 0.5, ylab="note", main=paste(cakeName, "grades from 0 to 4"),
          col=rainbow(5))
  text(1.5, 0.5, paste("Price:", data$price[1], "euros",
         "
Nb of cookies:", data$nb.of.cookies[1], "
              Price by cookie:", priceByCookie,"euros"))
}
```

```{r}
cakeList <- unique(grades$cake)
length <- length(unique(grades$cake))
cakeList[length]

meanList <- c()
for (i in cakeList){
  meanCake <-mean(grades$total[which (grades$cake==i)])
  names(meanCake) <- i
  meanList <- c(meanList, meanCake)
}
print(meanList)
par(mar=c(3,9,4,4))
barplot(sort(meanList), horiz=TRUE, las=1, 
        col=terrain.colors(length(meanList)) , main="Total grades for each cake")
```

```{r}
for (i in cakeList){
#  print (i)
  boxplotByCake(i, grades)
  meanCake <-mean(grades$total[which (grades$cake==i)])
  print("Note")
  print (meanCake)
}
```

